/*
export const SET_NORMAL_PLAYER = 'SET_NORMAL_PLAYER'
export const SET_MINI_PLAYER = 'SET_MINI_PLAYER'
export const SET_LIST_PLAYER = 'SET_LIST_PLAYER'
export const SET_PLAYING = 'SET_PLAYING'
export const SET_FAVORITE = 'SET_FAVORITE'
export const SET_PLAYER_TYPE = 'SET_PLAYER_TYPE'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_CUR_INDEX = 'SET_CUR_INDEX'
 */

export default {
  SET_NORMAL_PLAYER: 'SET_NORMAL_PLAYER',
  SET_MINI_PLAYER: 'SET_MINI_PLAYER',
  SET_LIST_PLAYER: 'SET_LIST_PLAYER',
  SET_PLAYING: 'SET_PLAYING',
  SET_FAVORITE: 'SET_FAVORITE',
  SET_PLAYER_TYPE: 'SET_PLAYER_TYPE',
  SET_PLAY_MODE: 'SET_PLAY_MODE',
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_CUR_INDEX: 'SET_CUR_INDEX',
  SET_CUR_LYRIC: 'SET_CUR_LYRIC',
  SET_SHOW_DISC: 'SET_SHOW_DISC'
}
